version: 2
jobs:
  build:
    docker:
      - image: commitsto/express
    environment:
      CODECOV_TOKEN: 0ee7c721-5f5c-48e3-985d-8f2bd8f30d7f
    working_directory: ~/commitsto
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run test:coverage
